import {
  useMemo,
  useState,
  QueryClient,
  QueryClientProvider,
  useQueryClient,
  ArrowRight,
  Bell,
  Check,
  CheckCircle2,
  CircleAlert,
  CircleDot,
  ClipboardList,
  Filter,
  HandHeart,
  LayoutDashboard,
  Leaf,
  LogOut,
  Menu,
  Package,
  Plus,
  RefreshCw,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Truck,
  Users,
  X,
  XCircle,
  Zap,
  Link,
  Route,
  Switch,
  WouterRouter,
  useLocation,
  useParams,
  useAcceptRequest,
  useCompleteRequest,
  useCreateRequest,
  useCreateResource,
  useDeleteResource,
  useGetAdminStats,
  useGetDashboard,
  useGetMe,
  useGetRequest,
  useGetResource,
  useListNgos,
  useListNotifications,
  useListRecommendations,
  useListRequests,
  useListResources,
  useListTransactions,
  useLogin,
  useLogout,
  useMarkNotificationRead,
  useRegister,
  useRejectRequest,
  useUpdateResource,
  useVerifyNgo,
  getGetAdminStatsQueryKey,
  getGetDashboardQueryKey,
  getGetMeQueryKey,
  getGetRequestQueryKey,
  getGetResourceQueryKey,
  getListNgosQueryKey,
  getListNotificationsQueryKey,
  getListRecommendationsQueryKey,
  getListRequestsQueryKey,
  getListResourcesQueryKey,
  getListTransactionsQueryKey,
  setAuthTokenGetter,
  Resource,
  ResourceRequest,
  User,
  ErrorBoundary,
  Toaster,
  TooltipProvider,
  NotFound,
  queryClient,
  categories,
  categoryLabel,
  formatDate,
  formatAgo,
  initials,
  humanStatus,
  Badge,
  Button,
  SectionTitle,
  StatCard,
  SkeletonList,
  EmptyState,
  ErrorState,
  navItems,
  Shell,
  AuthLayout,
  Field,
  InlineError,
  FormInput,
  ResourceRow,
  RequestMini,
} from "../components/app-shared";

function RequestsPage() {
  const [direction, setDirection] = useState('all'); const [status, setStatus] = useState(''); const [, setLocation] = useLocation(); const [selected, setSelected] = useState<number | null>(null); const qc = useQueryClient();
  const params = useMemo(() => ({ direction: direction as 'incoming' | 'outgoing' | 'all', status: status || undefined, page: 1, pageSize: 50 }), [direction, status]); const requests = useListRequests(params, { query: { queryKey: getListRequestsQueryKey(params) } }); const accept = useAcceptRequest(); const reject = useRejectRequest(); const complete = useCompleteRequest();
  const requestDetail = useGetRequest(selected ?? 0, { query: { enabled: Boolean(selected), queryKey: getGetRequestQueryKey(selected ?? 0) } });
  const mutate = (action: 'accept' | 'reject' | 'complete', id: number) => { const mutation = action === 'accept' ? accept : action === 'reject' ? reject : complete; mutation.mutate({ id }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListRequestsQueryKey() }); qc.invalidateQueries({ queryKey: getListTransactionsQueryKey() }); qc.invalidateQueries({ queryKey: getGetDashboardQueryKey() }); } }); };
  return <><SectionTitle eyebrow="Coordination queue" title="Requests" description="Keep commitments visible from first ask to completed handoff." action={<Button onClick={() => setLocation('/requests/new')} data-testid="button-new-request"><Plus size={16}/> Make a request</Button>}/><div className="mb-5 flex flex-wrap gap-2"><div className="flex rounded-lg border border-border bg-card p-1">{['all', 'incoming', 'outgoing'].map((item) => <button key={item} onClick={() => setDirection(item)} className={`rounded-md px-3 py-1.5 text-xs font-semibold capitalize ${direction === item ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:text-foreground'}`} data-testid={`button-direction-${item}`}>{item}</button>)}</div><select className="w-auto" value={status} onChange={(e) => setStatus(e.target.value)} data-testid="select-request-status"><option value="">Any status</option>{['open', 'accepted', 'rejected', 'completed'].map((s) => <option key={s} value={s}>{s}</option>)}</select></div>{requests.isLoading ? <SkeletonList rows={6}/> : requests.isError ? <ErrorState retry={() => requests.refetch()}/> : !requests.data?.items?.length ? <EmptyState icon={ClipboardList} title="No requests in this view" description="Requests will appear here as your network starts coordinating." action={<Button onClick={() => setLocation('/requests/new')} data-testid="button-empty-request"><Plus size={15}/> Create request</Button>}/> : <div className="space-y-3">{requests.data.items.map((request) => <div key={request.id} className="rounded-xl border border-card-border bg-card p-4 shadow-[0_2px_10px_hsl(194_30%_15%/.025)]" data-testid={`request-card-${request.id}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-start gap-3"><div className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-secondary text-primary"><ClipboardList size={17}/></div><div className="min-w-0"><button className="truncate text-left font-bold hover:text-primary" onClick={() => setSelected(request.id)} data-testid={`button-view-request-${request.id}`}>{request.resourceType}</button><p className="mt-1 text-xs text-muted-foreground">{request.requesterNgoName} Â· {request.location}</p><p className="mt-2 text-xs"><span className="font-mono font-bold">{request.quantity}</span> needed by {formatDate(request.requiredDate)}</p></div></div><div className="flex items-center gap-3"><Badge tone={request.urgency === 'critical' ? 'red' : request.urgency === 'high' ? 'orange' : 'muted'}>{request.urgency} urgency</Badge><Badge tone={request.status === 'open' ? 'blue' : request.status === 'completed' ? 'green' : 'muted'}>{humanStatus(request.status)}</Badge></div></div>{request.status === 'open' && <div className="mt-4 flex gap-2 border-t border-border pt-3 sm:justify-end"><Button variant="quiet" className="min-h-8 text-xs" onClick={() => mutate('reject', request.id)} data-testid={`button-reject-request-${request.id}`}><XCircle size={14}/> Decline</Button><Button className="min-h-8 text-xs" onClick={() => mutate('accept', request.id)} data-testid={`button-accept-request-${request.id}`}><CheckCircle2 size={14}/> Accept request</Button></div>}{request.status === 'accepted' && <div className="mt-4 flex justify-end border-t border-border pt-3"><Button className="min-h-8 text-xs" onClick={() => mutate('complete', request.id)} data-testid={`button-complete-request-${request.id}`}><Check size={14}/> Mark complete</Button></div>}</div>)}</div>}{selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/25 p-4" role="dialog" aria-modal="true" data-testid="dialog-request-detail"><div className="w-full max-w-md rounded-xl border border-card-border bg-card p-6 shadow-2xl"><div className="flex items-start justify-between"><div><div className="font-mono text-[10px] uppercase tracking-wider text-primary">Request detail</div><h2 className="mt-1 text-xl font-bold">{requestDetail.data?.resourceType ?? 'Loading request'}</h2></div><button onClick={() => setSelected(null)} className="rounded-lg p-2 hover:bg-muted" data-testid="button-close-request-detail"><X size={18}/></button></div>{requestDetail.data && <div className="mt-5 space-y-3 text-sm"><div className="flex justify-between border-b border-border pb-3"><span className="text-muted-foreground">Requested by</span><span className="font-semibold">{requestDetail.data.requesterNgoName}</span></div><div className="flex justify-between border-b border-border pb-3"><span className="text-muted-foreground">Quantity</span><span className="font-mono font-semibold">{requestDetail.data.quantity}</span></div><div className="flex justify-between border-b border-border pb-3"><span className="text-muted-foreground">Location</span><span className="font-semibold">{requestDetail.data.location}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Needed by</span><span className="font-semibold">{formatDate(requestDetail.data.requiredDate)}</span></div></div>}</div></div>}</>;
}

export default RequestsPage;
