import {
  useMemo,
  useState,
  QueryClient,
  QueryClientProvider,
  useQueryClient,
  ArrowRight,
  Bell,
  Check,
  CheckCircle2,
  CircleAlert,
  CircleDot,
  ClipboardList,
  Filter,
  HandHeart,
  LayoutDashboard,
  Leaf,
  LogOut,
  Menu,
  Package,
  Plus,
  RefreshCw,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Truck,
  Users,
  X,
  XCircle,
  Zap,
  Link,
  Route,
  Switch,
  WouterRouter,
  useLocation,
  useParams,
  useAcceptRequest,
  useCompleteRequest,
  useCreateRequest,
  useCreateResource,
  useDeleteResource,
  useGetAdminStats,
  useGetDashboard,
  useGetMe,
  useGetRequest,
  useGetResource,
  useListNgos,
  useListNotifications,
  useListRecommendations,
  useListRequests,
  useListResources,
  useListTransactions,
  useLogin,
  useLogout,
  useMarkNotificationRead,
  useRegister,
  useRejectRequest,
  useUpdateResource,
  useVerifyNgo,
  getGetAdminStatsQueryKey,
  getGetDashboardQueryKey,
  getGetMeQueryKey,
  getGetRequestQueryKey,
  getGetResourceQueryKey,
  getListNgosQueryKey,
  getListNotificationsQueryKey,
  getListRecommendationsQueryKey,
  getListRequestsQueryKey,
  getListResourcesQueryKey,
  getListTransactionsQueryKey,
  setAuthTokenGetter,
  Resource,
  ResourceRequest,
  User,
  ErrorBoundary,
  Toaster,
  TooltipProvider,
  NotFound,
  queryClient,
  categories,
  categoryLabel,
  formatDate,
  formatAgo,
  initials,
  humanStatus,
  Badge,
  Button,
  SectionTitle,
  StatCard,
  SkeletonList,
  EmptyState,
  ErrorState,
  navItems,
  Shell,
  AuthLayout,
  Field,
  InlineError,
  FormInput,
  ResourceRow,
  RequestMini,
} from "../components/app-shared";

function ResourcesPage() {
  const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [status, setStatus] = useState(''); const [, setLocation] = useLocation(); const [editing, setEditing] = useState<number | null>(null);
  const params = useMemo(() => ({ search: search || undefined, category: (category || undefined) as typeof categories[number] | undefined, status: status || undefined, page: 1, pageSize: 50 }), [search, category, status]);
  const resources = useListResources(params, { query: { queryKey: getListResourcesQueryKey(params) } }); const remove = useDeleteResource(); const update = useUpdateResource(); const qc = useQueryClient();
  const detail = useGetResource(editing ?? 0, { query: { enabled: Boolean(editing), queryKey: getGetResourceQueryKey(editing ?? 0) } });
  return <><SectionTitle eyebrow="Inventory" title="Available resources" description="Browse the live supply pool and find what can move next." action={<Button onClick={() => setLocation('/resources/new')} data-testid="button-new-resource"><Plus size={16}/> List a resource</Button>}/><div className="mb-5 grid gap-3 rounded-xl border border-card-border bg-card p-3 md:grid-cols-[1fr_180px_150px]"><div className="relative"><Search className="absolute left-3 top-3 text-muted-foreground" size={16}/><input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search resources, organizations, places" data-testid="input-search-resources"/></div><select value={category} onChange={(e) => setCategory(e.target.value)} data-testid="select-resource-category"><option value="">All categories</option>{categories.map((c) => <option key={c} value={c}>{categoryLabel(c)}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)} data-testid="select-resource-status"><option value="">All statuses</option><option value="available">Available</option><option value="reserved">Reserved</option><option value="depleted">Depleted</option></select></div>{resources.isLoading ? <SkeletonList rows={6}/> : resources.isError ? <ErrorState retry={() => resources.refetch()}/> : !resources.data?.items?.length ? <EmptyState title="Nothing matches yet" description="Try a different search or be the first to add a resource." action={<Button onClick={() => setLocation('/resources/new')} data-testid="button-empty-resource"><Plus size={15}/> Add resource</Button>}/> : <div className="overflow-hidden rounded-xl border border-card-border bg-card"><div className="hidden grid-cols-[1.5fr_1fr_.75fr_.8fr_100px] gap-4 border-b border-border bg-muted/45 px-5 py-3 font-mono text-[10px] uppercase tracking-wider text-muted-foreground md:grid"><span>Resource</span><span>Location</span><span>Quantity</span><span>Status</span><span/></div>{resources.data.items.map((resource) => <div key={resource.id} className="grid gap-3 border-b border-border px-4 py-4 last:border-b-0 md:grid-cols-[1.5fr_1fr_.75fr_.8fr_100px] md:items-center md:gap-4 md:px-5" data-testid={`resource-card-${resource.id}`}><div className="flex min-w-0 items-center gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-secondary text-primary"><Package size={16}/></div><div className="min-w-0"><div className="truncate text-sm font-bold">{resource.name}</div><div className="mt-1 text-xs capitalize text-muted-foreground">{categoryLabel(resource.category)} Â· {resource.ownerNgoName}</div></div></div><div className="text-xs text-muted-foreground">{resource.location}</div><div className="font-mono text-xs">{resource.quantity} {resource.unit}</div><div><Badge tone={resource.status === 'available' ? 'green' : resource.status === 'reserved' ? 'orange' : 'muted'}>{humanStatus(resource.status)}</Badge></div><div className="flex gap-1 md:justify-end"><Button variant="quiet" className="min-h-8 px-2 text-xs" onClick={() => setEditing(resource.id)} data-testid={`button-edit-resource-${resource.id}`}>Edit</Button><Button variant="quiet" className="min-h-8 px-2 text-xs" onClick={() => { if (window.confirm('Remove this resource listing?')) remove.mutate({ id: resource.id }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListResourcesQueryKey() }); qc.invalidateQueries({ queryKey: getGetDashboardQueryKey() }); } }); }} data-testid={`button-delete-resource-${resource.id}`}><X size={14}/> Remove</Button></div></div>)}</div>}{editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/25 p-4" role="dialog" aria-modal="true" data-testid="dialog-edit-resource"><div className="w-full max-w-lg rounded-xl border border-card-border bg-card p-6 shadow-2xl"><div className="flex items-center justify-between"><div><div className="font-mono text-[10px] uppercase tracking-wider text-primary">Edit listing</div><h2 className="mt-1 text-xl font-bold">{detail.data?.name ?? 'Loading resource'}</h2></div><button onClick={() => setEditing(null)} className="rounded-lg p-2 hover:bg-muted" data-testid="button-close-edit-resource"><X size={18}/></button></div>{detail.isLoading ? <div className="mt-6"><SkeletonList rows={3}/></div> : detail.data && <form className="mt-5 space-y-4" onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); update.mutate({ id: detail.data.id, data: { name: String(data.get('name')), quantity: Number(data.get('quantity')), unit: String(data.get('unit')), location: String(data.get('location')), status: String(data.get('status')) as 'available' | 'reserved' | 'depleted' | 'expired' } }, { onSuccess: () => { qc.invalidateQueries({ queryKey: getListResourcesQueryKey() }); setEditing(null); } }); }}><Field label="Resource name"><input name="name" defaultValue={detail.data.name} required data-testid="input-edit-resource-name"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Quantity"><input name="quantity" type="number" defaultValue={detail.data.quantity} required data-testid="input-edit-resource-quantity"/></Field><Field label="Unit"><input name="unit" defaultValue={detail.data.unit} required data-testid="input-edit-resource-unit"/></Field></div><Field label="Location"><input name="location" defaultValue={detail.data.location} required data-testid="input-edit-resource-location"/></Field><Field label="Status"><select name="status" defaultValue={detail.data.status} data-testid="select-edit-resource-status">{['available', 'reserved', 'depleted', 'expired'].map((s) => <option key={s} value={s}>{s}</option>)}</select></Field><Button className="w-full" type="submit" disabled={update.isPending} data-testid="button-save-resource">{update.isPending ? 'Savingâ€¦' : 'Save changes'}<Check size={15}/></Button></form>}</div></div>}</>;
}

export default ResourcesPage;
